#server:
#  port: 8761
#
#spring:
#  application:
#    name: esd-aom-service-discovery

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: '*' # Não é recomendado expor todos os endpoints

# Eureka settings
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: localhost