server:
  port: 8090

spring:
  application:
    name: esd-aom-gateway

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: '*' # Não é recomendado expor todos os endpoints

# Eureka settings
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

